config/routes.rb
Ghint::Application.routes.draw do

  resources :github_users do
    collection do
      get 'redirect'
    end
  end

  root :to => "home#index"
  devise_for :users

end

app/models/github_user.rb
class GithubUser < ActiveRecord::Base
  attr_accessible :login
  belongs_to :user
end

app/models/termination.rb
class Termination < ActiveRecord::Base
  attr_accessible :fullname, :location, :manager, :processed_by, :term_date, :username, :uuid

  def to_s
    "User '#{username}' termed at #{term_date}. ID: #{uuid}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :ldap_authenticatable, :trackable

  has_one :github_user

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username

  validates_presence_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from DeviseLdapAuthenticatable::LdapException do |exception|
    render :text => exception, :status => 500
  end
  protect_from_forgery
end

app/controllers/github_users_controller.rb
class GithubUsersController < ApplicationController

  def show
    @gh_user = current_user.github_user
  end

  def destroy
    current_user.github_user.delete
    redirect_to :action => 'new'
  end

  def redirect
    github = Github.new :client_id => ENV['GH_CLIENT_ID'], :client_secret => ENV['GH_CLIENT_SECRET']
    token = github.get_token(params[:code])
    logger.debug "Token: #{token.token}"

    github = Github.new oauth_token: token.token
    user = github.users.get

    g = GithubUser.where(:login => user[:login]).first_or_create do |gh_user|
      gh_user.gh_id = user[:id]
      gh_user.url = user[:url]
      gh_user.html_url = user[:html_url]
      gh_user.name = user[:name]
      gh_user.location = user[:location]
      gh_user.email = user[:email]
      gh_user.gh_created_at = user[:created_at]
      gh_user.public_repos = user[:public_repos]
      gh_user.private_repos = user[:total_private_repos]
      gh_user.avatar_url = user[:avatar_url]
      gh_user.user = current_user
      gh_user.save
    end

    # Add the user to the standard 'All Rackers group'
    AddUser.add current_user.username

    flash[:notice] = "Your Github and Rackspace accounts are now linked. Your account will now be added to the 'All Rackers' group in Github."
    redirect_to :action => 'show', :id => g.id
  end

  def new
    github = Github.new :client_id => ENV['GH_CLIENT_ID'], :client_secret => ENV['GH_CLIENT_SECRET']
    @gh_uri = github.authorize_url :scope => 'user'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
    if current_user.github_user.nil?
      redirect_to new_github_user_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_base_errors resource
    return '' if resource.errors.empty?
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

  def javascript_file_exists?(name)
    !Ghint::Application.assets.find_asset("#{name}.js").nil?
  end
end

app/helpers/github_users_helper.rb
module GithubUsersHelper
end

app/views/github_users/new.html.erb
<div class="hero-unit">
  <p>
    It looks like you haven't linked your GitHub account to your Rackspace SSO. You'll need to do
    that before you can be granted access to the Rackspace organization on Github. To get started
    you just have to authorize this app to your Github account using the OAuth link below.
  </p>

  <p>
    <%= image_tag "github-logo.png" %>
    <a class="btn btn-primary btn-large" href="<%= @gh_uri  %>">Sign In To GitHub »</a>
  </p>
</div>

app/views/github_users/show.html.erb
<div class="span3">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">Gravatar</li>
      <li>
        <%= image_tag @gh_user.avatar_url, :class => 'img-polaroid' %>
      </li>

      <li class="nav-header">Actions</li>
      <li style="padding-top: 15px;">
        <%= link_to "Unlink User", @gh_user, method: :delete, :class => "btn btn-medium", :style => "width: 100%" %>
      </li>
      <li style="padding-top: 15px;">
        <%= link_to "View Permissions", root_path, :class => "btn btn-medium", :disabled => true, :style => "width: 100%" %>
      </li>
    </ul>
  </div><!--/.well -->
</div>


<div class="span9">
  <%= render 'layouts/messages' %>
  <table class="table table-bordered table-striped">
    <tbody>
      <tr>
        <td>Github Login</td>
        <td><%= @gh_user.login %></td>
      </tr>
      <tr>
        <td>Github ID</td>
        <td><%= @gh_user.gh_id %></td>
      </tr>
      <tr>
        <td>User API URL</td>
        <td><a href="<%= @gh_user.url %>"><%= @gh_user.url %></a></td>
      </tr>
      <tr>
        <td>User HTML URL</td>
        <td><a href="<%= @gh_user.html_url %>"><%= @gh_user.html_url %></a></td>
      </tr>
      <tr>
        <td>Gravatar URL</td>
        <td><a href="<%= @gh_user.avatar_url %>"><%= truncate @gh_user.avatar_url, :length => 100 %></a></td>
      </tr>
      <tr>
        <td>Name</td>
        <td><%= @gh_user.name %></td>
      </tr>
      <tr>
        <td>Github Location</td>
        <td><%= @gh_user.location %></td>
      </tr>
      <tr>
        <td>Github Primary Email</td>
        <td><%= @gh_user.email %></td>
      </tr>
      <tr>
        <td>Created At</td>
        <td><%= @gh_user.gh_created_at %></td>
      </tr>
      <tr>
        <td>Private Repositories</td>
        <td><%= @gh_user.private_repos %></td>
      </tr>
      <tr>
        <td>Public Repositories</td>
        <td><%= @gh_user.public_repos %></td>
      </tr>
      <tr>
        <td>Last Updated</td>
        <td><%= @gh_user.updated_at %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/home/index.html.erb
<div class="span12">
  <h1>Welcome, <%=  current_user.username %>!</h1>

</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>

<%= link_to "Ghint", root_path, :class => 'brand' %>

<div class="nav-collapse collapse">
  <% if user_signed_in? %>
    <p class="navbar-text pull-right">
      <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
    </p>
    <ul class="nav">
      <li><a href="/">Home</a></li>
      <% unless current_user.github_user.nil? %>
        <li><%= link_to "Github User", github_user_path(current_user.github_user) %></li>
      <% end %>
    </ul>
  <% end %>
</div><!--/.nav-collapse -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Ghint" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ghint" %>">
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag params[:controller] if javascript_file_exists? params[:controller] %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>
<header class="navbar navbar-fixed-top">
  <nav class="navbar-inner">
    <div class="container">
      <%= render 'layouts/navigation' %>
    </div>
  </nav>
</header>
<div id="main" role="main">
  <div class="container">
    <div class="content">
      <div class="row">
        <%= yield %>
      </div>
      <footer>
      </footer>
    </div>
  </div> <!--! end of .container -->
</div> <!--! end of #main -->

<%= yield(:footer) %>
</body>
</html>